### ISSUE TITLE
Features list to be added/augmented/updated

### ISSUE THREAD

**Issue by alexislyndon** [alexislyndon/SecurityLogbook#1]
note: when taking tasks, edit and append your name like this:  _[WORKING: @alexislyndon ]_ make it **_BOLDitalic_**
mark it [DONE:axis] if done

### **MAIN VIEWS**

1. Main Gate View (Main gate computer/with "main" designation)
 -Vehicle entry [@MariaLizaPaano ]
2. Back Gate View (back gate computer/with "back" designation)
 -people only [@neil]
3. Admin View(security office/with "admin" designation)
 -Register new users / [@alexislyndon ]
 -no check in / check out options(can only view status)

### **TASKS**

- [x] camera image capture save how? **_[DONE: @alexislyndon ]_**
- [ ] form validation **_[WORKING: @alexislyndon ]_**

- [ ] optimize check in flow (make UI easier to work with; more intuitive)
- [ ] optimize check out flow (maybe we can use RFID - kung magpalit tag rfid reader?)
- [ ] create UI for **advanced search** (history tab maybe / separate from currently checked in visitors)
- [x] log out[**Done** @MariaLizaPaano  pero tan awa kung tama hahahah]
- [ ] session (the system knows who is logged in) [add to DB]
- [ ] activity logs(textfile/DB that stores some info about what happens in the app) [add to DB]
- [ ] Vehicle check in / check out functionality including database queries and form validation

### **Problems/Questions**

1. How to deal with the color coding? How should we design it?
2. Should we make a Dashboard? What info will be on the dashboard?
